hash-format = "sha256"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "7e19892b834ca681e69bff8b666ad7fb41c783d80e44826b9984056f15a1b781"

[[files]]
file = "config/yosbr/config/starterkit/starterkit.txt"
hash = "98e29fe814d5e77ee23f9631c3ae647b873e374f3df5dc2b1b4b53e232bccd92"

[[files]]
file = "config/yosbr/options.txt"
hash = "9187cba268ca7b365ce3f8a99198a95ebe748d6ea14db42b9c355c7e616005ff"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "6869de1ca55dc09beabb3c234727e84be4d4fbdcbad2c8081c03010713f374e1"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "b2e0d51beac88a90d9b9051c075890c862bd6e33483b45f69584af23e61dd7e5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a5eac6a8d140ee215411d88e61bf9b53a2a26021032b65cffc0924403475dbba"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "68a120db2b2c4db5fbfde501a6ee0504c692f3b1e777cc4dd85f1cb90c84dcd0"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "50e3b067e93d3e6683d540edc4d046ed7b6b5fbb31409df1727b120f225b1975"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1fc52599bb002e467661afaa4b844c517fb549ad14eb6f552bf11dfb5c8b535e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "5dc1b3414774e16c9fcdf4d5283457ac1a8df0c498851009157b62517de3fd5e"
metafile = true

[[files]]
file = "mods/command-macros.pw.toml"
hash = "be57a455bb8c8f01f1e9b18a32ab3079de5d5f09cd934bf9365e68fad95bfc21"
metafile = true

[[files]]
file = "mods/diggus-maximus.pw.toml"
hash = "db690311634819527b9455423d21dce9057a5f00292e8270a1b2baa28a063936"
metafile = true

[[files]]
file = "mods/durabilityviewer.pw.toml"
hash = "30fb402a2189537fbcad664b5ac28df0bc47e557b03af95117c10b58c86cc0fe"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "714158dafbd5954a8024d5b7e677fc1303d1c0bc665c7df5942d3a685904988e"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "6f95b9e670d557f852a798489d7b5ec48ed8ddc7e8e1809ff06d4b187d17aac9"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "0c4c20d601b15dbc85c275732d9efe9369597503c7d6caa9a7fee217f67073e7"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
hash = "7325f217817b1793fce374f9e71280a57fb02af18f4c6175e9ae10b267272470"
metafile = true

[[files]]
file = "mods/fld.pw.toml"
hash = "55a95a2981ebeb0b5712d9feffb967269821633576817468191e3eef5d5bce5e"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "e00070f0db00ebcd304f8f68fd44e59ceaedbc8c27743c9c195134aae57c5fde"
metafile = true

[[files]]
file = "mods/glsl-panorama.pw.toml"
hash = "22785ac1be221752745af6018e9323c0f90b918478483b601e4b783b4efe7d98"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "a4d47f10df4769734a850e6a2cd7342802f92f5e269b27464c86cfd0b5a2182f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "0c5e71addef34c8dcd1c81dfc2ad851a3e274b9d8d3a7d388e1113d4139bf8d8"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7df52a269aaabcb9c4d3ce72322177f4cb5d2e8fc8d506554fa6b6290b0ad548"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "c5d5b857fa70cb5deed260054b9723dc8069635880061d5ba328e1eb684604bf"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e43d696d9a6546f3b622a1242c42d3ec34d3a0739225b9b51319c9402f09041b"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
hash = "e5baa5b81dbd3dda0e75a524c10302d278fceee4be251cdbee2a48bf3eae1f94"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "050c95aa9ef6b9f7eb32f3ac51bd6b13e307468d9b83e0fa7720dddabfd1fc5a"
metafile = true

[[files]]
file = "mods/litematica-printer.pw.toml"
hash = "3aa4802505046aeeb8f9a2f13a7750cc0263cea111ab488fb28a9d71a3e47984"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "aac087baa5cda20dea324cebd9076991e4802561702b11292d96bdbc6ed15472"
metafile = true

[[files]]
file = "mods/midnightcontrols-extra.pw.toml"
hash = "563a2484af46ebe381f606733cce8e75450dc8de141a115bb82120ddfc47d535"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "bda1dd1e157c3db8fba22bab8bda6062cbb1c598ba787ae7404550a7ad95ea5e"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "54e445b0b16e34991e7c2e2475905c1c36a65f7103ba9e4af05fe0df09160c4b"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "b136ca50e7d8239319f528ceb521e3482f753b25d768afaf39fa6ea81e549f2e"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "669008dbd2508a67f8c409096cf2357de450f26a69494289e5852045ade7d358"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "19a098ab3131eb6daf0033199744d33dbb31a4ce9b20b9fc6eb709ab1272aa7e"
metafile = true

[[files]]
file = "mods/replaymod.pw.toml"
hash = "9e7c1e6cf3b81dce5a77bf5c95ed9d8e9b936b932aeadb1255245234230ced16"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "17b4cf782db225c145f5c2ababe1042deb0fed021f410d42691829673fa916c3"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "7e39ba5b471407bf43c212fae99856276bf4411046aa3a5df5a7d27e76c7a2b3"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "c2fb8a64bc4610b7d026dc4cce78ad2a2f7264e5be4755849187e3caed5cac55"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9a927c3e0830ba32e1b8a2e543597781724462595b8cce58f676962b442bb52b"
metafile = true

[[files]]
file = "mods/starter-kit.pw.toml"
hash = "48cdf89fd831068e391a00ae7f4ab0a588eaa860d5356435d5c447e4989d29ab"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "94dbdfe3831f0adbcbf9e1ed1a9d86eb7d5141ef10ebf6bf0a9d05713a21c9c6"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "d84cd8cdfc4159872ffb18d41da94c1c525a725a8b4ec2b0818358d14fd4ca83"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "820c7a11a6d105ee6b8e4faaf0b93f807fcdbc803f816437e2170c76c439e38c"
metafile = true

[[files]]
file = "shaderpacks/complementary-shaders-v4.pw.toml"
hash = "356650c70469f8597be3f7a99067ad397202bd091336218b588ebf0bb4856e51"
metafile = true

[[files]]
file = "shaderpacks/rethinking-voxels.pw.toml"
hash = "b71aae4389aa77112335858465e31b13f8bbdc4a1c60a0a54ceb6338e339ce1b"
metafile = true

[[files]]
file = "starterkit/starterkit.txt"
hash = "05bb85e48174b0153a15842377217c3e7c8c6659c2cd8abd73b2de2ba72ac14d"
